### ISSUE TITLE
Help with finger print scanner

### ISSUE THREAD

**Issue by TheWayOfTheDeer** [ToniCorinne/BoardDesigns#1]
Hello, I am very new at Arduino projects and I cannot get my fingerprint scanner code to work. It was a code that you contributed to so i thought i would ask you to help.
I wanted to run a simple code that would blink an LED 
(the code)
https://github.com/sparkfun/Fingerprint_Scanner-TTL/blob/master/FPS_GT511C3/Examples/FPS_Blink/FPS_Blink.ino
When I try to run it, i get an error that says "error: FPS_GT511C3.h: No such file or directory"
as well as " error: 'FPS_GT511C3' does not name a type"
Any help would be much appreciated,
theWayOfTheDeer

**Comment by ToniCorinne** [comment]
Hey @TheWayOfTheDeer! This is a pretty common error, and it's usually due to the code library not being installed properly. Check out a tutorial on how to install the Arduino library correctly [here](https://learn.sparkfun.com/tutorials/installing-an-arduino-library). That should get rid of those errors you are currently seeing.

**Comment by TheWayOfTheDeer** [comment]
Thank you so much!

**Comment by TheWayOfTheDeer** [comment]
I downloaded the Library exactly as that source told me to and the error still persists. Do you have any other ideas of what the problem could be?

**Comment by TheWayOfTheDeer** [comment]
I can download other codes from github fine and I can obtain their Libraries too. When I try to import the library from the Fingerprint sensor a blank space gets placed into the code.

**Comment by ToniCorinne** [comment]
I'm not sure I understand what you mean by a blank space being placed in the code. If you can post an example, that will be more beneficial to see.

**Comment by TheWayOfTheDeer** [comment]
I actually figured it out. I was putting the "fingerprintScannerTTLmaster"
folder in the arduino libraries folder instead of the "FPS_GT511C3" folder
which was one layer deeper. Thank you though for the link you showed me and
for your code.

On Mon, Apr 27, 2015 at 2:37 PM, Toni Klopfenstein <notifications@github.com

**Comment by ToniCorinne** [comment]
Gad to hear you figured it out! Enjoy hacking on your project :)
